### PR TITLE
Sonar 6.7

### PR DESCRIPTION
**Pull request by avanishp**
Made compatible with sonar 6.7 and added support for multi-module project.

---
This change is [Reviewable](https://reviewable.io/reviews/sgoertzen/sonar-break-maven-plugin/75)

### CODE REVIEW

**Comment by avanishp** [comment]
@sgoertzen Can we have a look at this PR. Solves #48

**Comment by sgoertzen** [comment]
I'll check it out tomorrow, thanks so much for doing this!

**Comment by avanishp** [comment]
@sgoertzen Thanks. Would you be releasing this ? without the SNAPSHOT version?

**Comment by sgoertzen** [comment]
Yeah, I'll need to remove that versioning and push it up.  I'm having issues signing the jar right now, but hopefully I can get that figured out shortly.

**Comment by avanishp** [comment]
Cool. Thanks.

**Pull request merged**
